## example Makefile for parallel processing of dependencies

SEQ = $(shell seq 1 521)
$(info SEQ = ${SEQ})

BINS = $(shell echo test/*.bash)
$(info BINS is ${BINS})

.PHONY: $(BINS)
run: $(BINS)

test/*.bash:
	cat ./$@
	cp ./$@ ./$@.$$$$

